package com.sande.mythictrpg.raid;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sande.mythictrpg.condition.api.ConditionNode;
import com.sande.mythictrpg.condition.engine.ConditionTreeParser;
import com.sande.mythictrpg.condition.registry.ConditionTypeRegistry;
import com.sande.mythictrpg.quest.reward.RewardEntry;
import com.sande.mythictrpg.quest.reward.RewardEntryCodec;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/** Authored policy, not generated by the LLM. File paths are the canonical definition IDs. */
public record RaidDefinition(ResourceLocation id, String displayName, Mode mode,
        List<ResourceLocation> arenaIds, int minimumPlayers, int maximumPlayers,
        int queueTimeoutTicks, int combatTimeoutTicks, int livesPerPlayer, int disconnectGraceTicks,
        Boss boss, List<Phase> phases, ConditionNode entryCondition, RewardEligibility rewardEligibility,
        Set<ResourceLocation> offerGodIds, ResourceLocation rewardGodId, List<RewardEntry> rewards, String frozenJson) {
    public enum Mode { PUBLIC_WORLD, PARTY_ISOLATED }
    public enum RewardEligibility { ALL_FROZEN_ROSTER, SURVIVING_PRESENT }
    public record Boss(Optional<ResourceLocation> entityType, Optional<ResourceLocation> godId) { }
    public record Spawn(ResourceLocation entityType, int count, Vec3 offset) { }
    public record Phase(double atHealthRatio, List<Spawn> spawns) { }
    public record Arena(ResourceLocation id, ResourceLocation dimension, AABB bounds,
            Vec3 entry, Vec3 bossSpawn, Vec3 exit, String frozenJson) { }

    public static RaidDefinition parse(ResourceLocation id, JsonObject json) {
        keys(json, "schemaVersion", "displayName", "mode", "arenas", "minimumPlayers", "maximumPlayers",
                "queueTimeoutTicks", "combatTimeoutTicks", "livesPerPlayer", "disconnectGraceTicks", "boss",
                "phases", "entryCondition", "rewardEligibility", "offerGodIds", "rewardGodId", "rewards");
        integer(json, "schemaVersion", 1, 1);
        if (json.toString().length() > 64_000) throw new IllegalArgumentException("Raid definition exceeds 64000 characters");
        Mode mode = Mode.valueOf(string(json, "mode"));
        var arenas = new ArrayList<ResourceLocation>();
        for (var value : array(json, "arenas", 1, 16)) arenas.add(id(value.getAsString()));
        if (arenas.stream().distinct().count() != arenas.size()) throw new IllegalArgumentException("Duplicate arena");
        int minimum = integer(json, "minimumPlayers", 1, 32), maximum = integer(json, "maximumPlayers", minimum, 32);
        var boss = object(json, "boss"); keys(boss, "entityType", "godId");
        if (boss.has("entityType") == boss.has("godId")) throw new IllegalArgumentException("Boss requires exactly one entityType or godId");
        var definition = new Boss(optionalId(boss, "entityType"), optionalId(boss, "godId"));
        var phases = new ArrayList<Phase>();
        double previous = 1;
        if (json.has("phases")) for (var raw : array(json, "phases", 0, 8)) {
            var phase = raw.getAsJsonObject(); keys(phase, "atHealthRatio", "spawns");
            double ratio = number(phase, "atHealthRatio", 0.001, 0.999);
            if (ratio >= previous) throw new IllegalArgumentException("Phases must have strictly decreasing health ratios");
            previous = ratio;
            var spawns = new ArrayList<Spawn>(); int total = 0;
            for (var spawnRaw : array(phase, "spawns", 1, 8)) {
                var spawn = spawnRaw.getAsJsonObject(); keys(spawn, "entityType", "count", "offset");
                int count = integer(spawn, "count", 1, 16); total += count;
                spawns.add(new Spawn(id(string(spawn, "entityType")), count, vector(spawn, "offset", 32)));
            }
            if (total > 32) throw new IllegalArgumentException("Phase exceeds 32 reinforcements");
            phases.add(new Phase(ratio, List.copyOf(spawns)));
        }
        var rewards = new ArrayList<RewardEntry>();
        for (var raw : array(json, "rewards", 0, 32)) rewards.add(RewardEntryCodec.parse(raw.getAsJsonObject(), "raid.rewards"));
        ConditionNode condition = new ConditionTreeParser(ConditionTypeRegistry.INSTANCE).parse(json.get("entryCondition"));
        RewardEligibility rewardEligibility = RewardEligibility.valueOf(string(json, "rewardEligibility"));
        Set<ResourceLocation> offers = new LinkedHashSet<>();
        if (json.has("offerGodIds")) for (var offered : array(json, "offerGodIds", 0, 32))
            if (!offers.add(id(offered.getAsString()))) throw new IllegalArgumentException("Duplicate offer God ID");
        return new RaidDefinition(id, bounded(string(json, "displayName"), 128), mode, List.copyOf(arenas), minimum, maximum,
                integer(json, "queueTimeoutTicks", 20, 1_728_000), integer(json, "combatTimeoutTicks", 20, 1_728_000),
                integer(json, "livesPerPlayer", 1, 100), integer(json, "disconnectGraceTicks", 0, 72_000),
                definition, List.copyOf(phases), condition, rewardEligibility, Set.copyOf(offers),
                id(string(json, "rewardGodId")), List.copyOf(rewards), json.toString());
    }

    public static Arena parseArena(ResourceLocation id, JsonObject json) {
        keys(json, "schemaVersion", "dimension", "minimum", "maximum", "entry", "bossSpawn", "exit");
        integer(json, "schemaVersion", 1, 1);
        Vec3 min = vector(json, "minimum", 29_999_000), max = vector(json, "maximum", 29_999_000);
        if (max.x - min.x < 4 || max.y - min.y < 4 || max.z - min.z < 4
                || max.x - min.x > 128 || max.y - min.y > 128 || max.z - min.z > 128)
            throw new IllegalArgumentException("Arena dimensions must each be 4..128 blocks");
        AABB bounds = new AABB(min, max);
        Vec3 entry = vector(json, "entry", 29_999_000), boss = vector(json, "bossSpawn", 29_999_000), exit = vector(json, "exit", 29_999_000);
        if (!bounds.deflate(1).contains(entry) || !bounds.deflate(1).contains(boss) || bounds.inflate(2).contains(exit))
            throw new IllegalArgumentException("Entry/boss must be inside the arena and exit must be outside it");
        return new Arena(id, id(string(json, "dimension")), bounds, entry, boss, exit, json.toString());
    }

    public static ResourceLocation id(String value) {
        ResourceLocation result = ResourceLocation.tryParse(value);
        if (result == null || !value.contains(":")) throw new IllegalArgumentException("Expected namespaced ID: " + value);
        return result;
    }
    private static Optional<ResourceLocation> optionalId(JsonObject json, String key) {
        return json.has(key) ? Optional.of(id(string(json, key))) : Optional.empty();
    }
    private static void keys(JsonObject json, String... allowed) {
        var known = Set.of(allowed);
        for (String key : json.keySet()) if (!known.contains(key)) throw new IllegalArgumentException("Unknown field: " + key);
    }
    private static String string(JsonObject json, String key) {
        var v = json.get(key);
        if (v == null || !v.isJsonPrimitive() || !v.getAsJsonPrimitive().isString() || v.getAsString().isBlank())
            throw new IllegalArgumentException("Expected string: " + key);
        return v.getAsString();
    }
    private static String bounded(String value, int limit) {
        if (value.length() > limit) throw new IllegalArgumentException("Text too long");
        return value;
    }
    private static double number(JsonObject json, String key, double min, double max) {
        var v = json.get(key);
        if (v == null || !v.isJsonPrimitive() || !v.getAsJsonPrimitive().isNumber()) throw new IllegalArgumentException("Expected number: " + key);
        double n = v.getAsDouble();
        if (!Double.isFinite(n) || n < min || n > max) throw new IllegalArgumentException("Number out of range: " + key);
        return n;
    }
    private static int integer(JsonObject json, String key, int min, int max) {
        double n = number(json, key, min, max);
        if (n != Math.floor(n)) throw new IllegalArgumentException("Expected integer: " + key);
        return (int) n;
    }
    private static JsonObject object(JsonObject json, String key) {
        if (!json.has(key) || !json.get(key).isJsonObject()) throw new IllegalArgumentException("Expected object: " + key);
        return json.getAsJsonObject(key);
    }
    private static JsonArray array(JsonObject json, String key, int min, int max) {
        if (!json.has(key) || !json.get(key).isJsonArray()) throw new IllegalArgumentException("Expected array: " + key);
        var array = json.getAsJsonArray(key);
        if (array.size() < min || array.size() > max) throw new IllegalArgumentException("Array size out of range: " + key);
        return array;
    }
    private static Vec3 vector(JsonObject json, String key, double bound) {
        var a = array(json, key, 3, 3); double[] values = new double[3];
        for (int i = 0; i < 3; i++) {
            JsonElement e = a.get(i);
            if (!e.isJsonPrimitive() || !e.getAsJsonPrimitive().isNumber()) throw new IllegalArgumentException("Expected coordinate: " + key);
            values[i] = e.getAsDouble();
            if (!Double.isFinite(values[i]) || Math.abs(values[i]) > bound) throw new IllegalArgumentException("Coordinate out of range: " + key);
        }
        return new Vec3(values[0], values[1], values[2]);
    }
}
