package com.sande.mythictrpg.ai.reaction;

public enum ReactionGuidelineId {
    FIRST_ENCOUNTER,
    TIME_GREETING,
    LONG_TIME_REUNION,
    REPEATED_CONVERSATION,
    WEATHER_CHANGE,
    LOW_HEALTH,
    POST_COMBAT,
    QUEST_REQUEST,
    QUEST_INCOMPLETE,
    QUEST_COMPLETED,
    PREFERRED_GIFT,
    DISLIKED_GIFT,
    REPEATED_GIFT,
    COMPLIMENT,
    INSULT,
    APOLOGY,
    ASK_ABOUT_OTHER_GOD,
    UNKNOWN_INFORMATION
}
